# Generated by Django 6.0 on 2025-12-06 23:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleResource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sensitivity", models.CharField(default="normal", max_length=32)),
                ("pii_flags", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=255)),
                (
                    "org",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.org"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.team",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="api_sampler_name_76b803_idx")],
            },
        ),
    ]
