# Generated by Django 6.0 on 2025-12-07 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_audit_integrity_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUserProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=64)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=64)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auth_provider', models.CharField(default='local', help_text='Authentication provider: local, oidc, or both', max_length=32)),
                ('roles', models.JSONField(blank=True, default=list, help_text='User roles: platform_admin, org_admin, user, etc.')),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Local User Profile',
                'verbose_name_plural': 'Local User Profiles',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_sequenc_ae3403_idx',
            old_name='api_auditlo_sequenc_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationlog',
            new_name='api_imperso_admin_i_270c57_idx',
            old_name='api_impers_admin_i_c8e1a3_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationlog',
            new_name='api_imperso_target__8f91bd_idx',
            old_name='api_impers_target__f2a9b4_idx',
        ),
        migrations.RenameIndex(
            model_name='sensitiveuserdata',
            new_name='api_sensiti_user_id_32431a_idx',
            old_name='api_sensiti_user_id_4a7b8c_idx',
        ),
        migrations.AddField(
            model_name='localuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='localuserprofile',
            index=models.Index(fields=['email_verification_token'], name='api_localus_email_v_f41d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='localuserprofile',
            index=models.Index(fields=['password_reset_token'], name='api_localus_passwor_ec2479_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token_hash'], name='api_refresh_token_h_fd01e8_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'revoked_at'], name='api_refresh_user_id_c4ad3e_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='api_refresh_expires_661feb_idx'),
        ),
    ]
