# Generated by Django 6.0 on 2025-12-08 00:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_local_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='Platform', help_text='The name displayed in the browser tab and header', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='', help_text='URL to the site logo image', max_length=500)),
                ('favicon_url', models.URLField(blank=True, default='', help_text='URL to the favicon', max_length=500)),
                ('primary_color', models.CharField(default='#10b981', help_text='Primary brand color (hex format, e.g., #10b981)', max_length=7)),
                ('support_email', models.EmailField(blank=True, default='', help_text='Support email address displayed to users', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
