# Generated by Django 6.0 on 2025-12-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Billing contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe customer ID for billing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Active Stripe subscription ID', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['stripe_customer_id'], name='api_org_stripe__1b59ee_idx'),
        ),
    ]
