# Generated by Django 6.0 on 2025-12-08 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_stripe_fields_to_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localuserprofile',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='User-specific feature flags from subscription'),
        ),
        migrations.AddField(
            model_name='localuserprofile',
            name='license_tier',
            field=models.CharField(default='free', help_text="User's subscription tier: free, starter, pro, enterprise", max_length=64),
        ),
        migrations.AddField(
            model_name='localuserprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe customer ID for user billing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='localuserprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Active Stripe subscription ID', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='localuserprofile',
            index=models.Index(fields=['stripe_customer_id'], name='api_localus_stripe__33bbe3_idx'),
        ),
    ]
