# Generated by Django 6.0 on 2025-12-09 04:24

import api.encryption
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('access_key_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('secret_access_key', api.encryption.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access key pair',
                'verbose_name_plural': 'Access key pairs',
                'ordering': ['-created_at'],
            },
        ),
    ]
