# Generated by Django 6.0 on 2025-12-12 04:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_social_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='division_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('billing_mode', models.CharField(choices=[('inherit', 'Inherit from Org'), ('independent', 'Independent Billing')], default='inherit', max_length=16)),
                ('license_tier', models.CharField(blank=True, max_length=64)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='api.org')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membership',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.division'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.division'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'org', 'division', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('org', 'division', 'name')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['division'], name='api_members_divisio_c5a7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['division'], name='api_team_divisio_56db48_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['org'], name='api_divisio_org_id_48d734_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['billing_mode'], name='api_divisio_billing_af23e9_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['stripe_customer_id'], name='api_divisio_stripe__ed5cc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('org', 'name')},
        ),
    ]
