# Generated by Django 6.0 on 2025-12-16 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_division_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='family_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='api.refreshtoken'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['family_id'], name='api_refresh_family__6df41c_idx'),
        ),
    ]
