# Generated by Django 6.0 on 2025-12-06 23:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("license_tier", models.CharField(default="free", max_length=64)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="api_org_status_777c61_idx"),
                    models.Index(fields=["license_tier"], name="api_org_license_d0c7aa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="api.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("org_roles", models.JSONField(blank=True, default=list)),
                ("team_roles", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.org",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("org", "Org")],
                        default="global",
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("value", models.JSONField()),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scope", "key"], name="api_setting_scope_a360d5_idx"),
                    models.Index(fields=["org", "key"], name="api_setting_org_id_10ce78_idx"),
                ],
                "unique_together": {("scope", "org", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["org"], name="api_team_org_id_83cb15_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("org", "name")},
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user", "org"], name="api_members_user_id_f538dd_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["org"], name="api_members_org_id_7b25ee_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["team"], name="api_members_team_id_83aba8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "org", "team")},
        ),
    ]
