# Generated by Django 6.0 on 2025-12-07 03:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auditlog_emaillog_webhookendpoint_webhookdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("admin_id", models.CharField(db_index=True, max_length=255)),
                ("admin_email", models.CharField(blank=True, max_length=255, null=True)),
                ("target_user_id", models.CharField(db_index=True, max_length=255)),
                ("target_user_email", models.CharField(blank=True, max_length=255, null=True)),
                ("org_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("action", models.CharField(max_length=64)),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin_id", "created_at"], name="api_impers_admin_i_c8e1a3_idx"
                    ),
                    models.Index(
                        fields=["target_user_id", "created_at"],
                        name="api_impers_target__f2a9b4_idx",
                    ),
                ],
            },
        ),
    ]
