/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrgRouteImport } from './routes/org'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgLayoutRouteImport } from './routes/org/_layout'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as OrgLayoutIndexRouteImport } from './routes/org/_layout/index'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as OrgLayoutWebhooksIndexRouteImport } from './routes/org/_layout/webhooks/index'
import { Route as OrgLayoutUsersIndexRouteImport } from './routes/org/_layout/users/index'
import { Route as OrgLayoutTeamsIndexRouteImport } from './routes/org/_layout/teams/index'
import { Route as OrgLayoutSettingsIndexRouteImport } from './routes/org/_layout/settings/index'
import { Route as OrgLayoutDivisionsIndexRouteImport } from './routes/org/_layout/divisions/index'
import { Route as OrgLayoutBillingIndexRouteImport } from './routes/org/_layout/billing/index'
import { Route as OrgLayoutAuditIndexRouteImport } from './routes/org/_layout/audit/index'
import { Route as AppLayoutProfileIndexRouteImport } from './routes/app/_layout/profile/index'
import { Route as AppLayoutNotificationsIndexRouteImport } from './routes/app/_layout/notifications/index'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AdminLayoutTeamsIndexRouteImport } from './routes/admin/_layout/teams/index'
import { Route as AdminLayoutSettingsIndexRouteImport } from './routes/admin/_layout/settings/index'
import { Route as AdminLayoutPoliciesIndexRouteImport } from './routes/admin/_layout/policies/index'
import { Route as AdminLayoutOrganizationsIndexRouteImport } from './routes/admin/_layout/organizations/index'
import { Route as AdminLayoutMonitoringIndexRouteImport } from './routes/admin/_layout/monitoring/index'
import { Route as AdminLayoutDivisionsIndexRouteImport } from './routes/admin/_layout/divisions/index'
import { Route as AdminLayoutAuditIndexRouteImport } from './routes/admin/_layout/audit/index'
import { Route as AdminLayoutUsersUserIdRouteImport } from './routes/admin/_layout/users/$userId'
import { Route as AdminLayoutTeamsTeamIdRouteImport } from './routes/admin/_layout/teams/$teamId'
import { Route as AdminLayoutOrganizationsOrgIdRouteImport } from './routes/admin/_layout/organizations/$orgId'
import { Route as OrgLayoutDivisionsDivisionIdIndexRouteImport } from './routes/org/_layout/divisions/$divisionId/index'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgLayoutRoute = OrgLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OrgRoute,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const OrgLayoutIndexRoute = OrgLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const OrgLayoutWebhooksIndexRoute = OrgLayoutWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutUsersIndexRoute = OrgLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutTeamsIndexRoute = OrgLayoutTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutSettingsIndexRoute = OrgLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutDivisionsIndexRoute = OrgLayoutDivisionsIndexRouteImport.update({
  id: '/divisions/',
  path: '/divisions/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutBillingIndexRoute = OrgLayoutBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const OrgLayoutAuditIndexRoute = OrgLayoutAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => OrgLayoutRoute,
} as any)
const AppLayoutProfileIndexRoute = AppLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutNotificationsIndexRoute =
  AppLayoutNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTeamsIndexRoute = AdminLayoutTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsIndexRoute =
  AdminLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutPoliciesIndexRoute =
  AdminLayoutPoliciesIndexRouteImport.update({
    id: '/policies/',
    path: '/policies/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutOrganizationsIndexRoute =
  AdminLayoutOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMonitoringIndexRoute =
  AdminLayoutMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDivisionsIndexRoute =
  AdminLayoutDivisionsIndexRouteImport.update({
    id: '/divisions/',
    path: '/divisions/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAuditIndexRoute = AdminLayoutAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUsersUserIdRoute = AdminLayoutUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTeamsTeamIdRoute = AdminLayoutTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrganizationsOrgIdRoute =
  AdminLayoutOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const OrgLayoutDivisionsDivisionIdIndexRoute =
  OrgLayoutDivisionsDivisionIdIndexRouteImport.update({
    id: '/divisions/$divisionId/',
    path: '/divisions/$divisionId/',
    getParentRoute: () => OrgLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/app': typeof AppLayoutRouteWithChildren
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgLayoutRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/app/': typeof AppLayoutIndexRoute
  '/org/': typeof OrgLayoutIndexRoute
  '/admin/organizations/$orgId': typeof AdminLayoutOrganizationsOrgIdRoute
  '/admin/teams/$teamId': typeof AdminLayoutTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/admin/audit': typeof AdminLayoutAuditIndexRoute
  '/admin/divisions': typeof AdminLayoutDivisionsIndexRoute
  '/admin/monitoring': typeof AdminLayoutMonitoringIndexRoute
  '/admin/organizations': typeof AdminLayoutOrganizationsIndexRoute
  '/admin/policies': typeof AdminLayoutPoliciesIndexRoute
  '/admin/settings': typeof AdminLayoutSettingsIndexRoute
  '/admin/teams': typeof AdminLayoutTeamsIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
  '/app/notifications': typeof AppLayoutNotificationsIndexRoute
  '/app/profile': typeof AppLayoutProfileIndexRoute
  '/org/audit': typeof OrgLayoutAuditIndexRoute
  '/org/billing': typeof OrgLayoutBillingIndexRoute
  '/org/divisions': typeof OrgLayoutDivisionsIndexRoute
  '/org/settings': typeof OrgLayoutSettingsIndexRoute
  '/org/teams': typeof OrgLayoutTeamsIndexRoute
  '/org/users': typeof OrgLayoutUsersIndexRoute
  '/org/webhooks': typeof OrgLayoutWebhooksIndexRoute
  '/org/divisions/$divisionId': typeof OrgLayoutDivisionsDivisionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/app': typeof AppLayoutIndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgLayoutIndexRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/organizations/$orgId': typeof AdminLayoutOrganizationsOrgIdRoute
  '/admin/teams/$teamId': typeof AdminLayoutTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/admin/audit': typeof AdminLayoutAuditIndexRoute
  '/admin/divisions': typeof AdminLayoutDivisionsIndexRoute
  '/admin/monitoring': typeof AdminLayoutMonitoringIndexRoute
  '/admin/organizations': typeof AdminLayoutOrganizationsIndexRoute
  '/admin/policies': typeof AdminLayoutPoliciesIndexRoute
  '/admin/settings': typeof AdminLayoutSettingsIndexRoute
  '/admin/teams': typeof AdminLayoutTeamsIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
  '/app/notifications': typeof AppLayoutNotificationsIndexRoute
  '/app/profile': typeof AppLayoutProfileIndexRoute
  '/org/audit': typeof OrgLayoutAuditIndexRoute
  '/org/billing': typeof OrgLayoutBillingIndexRoute
  '/org/divisions': typeof OrgLayoutDivisionsIndexRoute
  '/org/settings': typeof OrgLayoutSettingsIndexRoute
  '/org/teams': typeof OrgLayoutTeamsIndexRoute
  '/org/users': typeof OrgLayoutUsersIndexRoute
  '/org/webhooks': typeof OrgLayoutWebhooksIndexRoute
  '/org/divisions/$divisionId': typeof OrgLayoutDivisionsDivisionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/org/_layout': typeof OrgLayoutRouteWithChildren
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/org/_layout/': typeof OrgLayoutIndexRoute
  '/admin/_layout/organizations/$orgId': typeof AdminLayoutOrganizationsOrgIdRoute
  '/admin/_layout/teams/$teamId': typeof AdminLayoutTeamsTeamIdRoute
  '/admin/_layout/users/$userId': typeof AdminLayoutUsersUserIdRoute
  '/admin/_layout/audit/': typeof AdminLayoutAuditIndexRoute
  '/admin/_layout/divisions/': typeof AdminLayoutDivisionsIndexRoute
  '/admin/_layout/monitoring/': typeof AdminLayoutMonitoringIndexRoute
  '/admin/_layout/organizations/': typeof AdminLayoutOrganizationsIndexRoute
  '/admin/_layout/policies/': typeof AdminLayoutPoliciesIndexRoute
  '/admin/_layout/settings/': typeof AdminLayoutSettingsIndexRoute
  '/admin/_layout/teams/': typeof AdminLayoutTeamsIndexRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
  '/app/_layout/notifications/': typeof AppLayoutNotificationsIndexRoute
  '/app/_layout/profile/': typeof AppLayoutProfileIndexRoute
  '/org/_layout/audit/': typeof OrgLayoutAuditIndexRoute
  '/org/_layout/billing/': typeof OrgLayoutBillingIndexRoute
  '/org/_layout/divisions/': typeof OrgLayoutDivisionsIndexRoute
  '/org/_layout/settings/': typeof OrgLayoutSettingsIndexRoute
  '/org/_layout/teams/': typeof OrgLayoutTeamsIndexRoute
  '/org/_layout/users/': typeof OrgLayoutUsersIndexRoute
  '/org/_layout/webhooks/': typeof OrgLayoutWebhooksIndexRoute
  '/org/_layout/divisions/$divisionId/': typeof OrgLayoutDivisionsDivisionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/org'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/'
    | '/app/'
    | '/org/'
    | '/admin/organizations/$orgId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/admin/audit'
    | '/admin/divisions'
    | '/admin/monitoring'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/users'
    | '/app/notifications'
    | '/app/profile'
    | '/org/audit'
    | '/org/billing'
    | '/org/divisions'
    | '/org/settings'
    | '/org/teams'
    | '/org/users'
    | '/org/webhooks'
    | '/org/divisions/$divisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/org'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/organizations/$orgId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
    | '/admin/audit'
    | '/admin/divisions'
    | '/admin/monitoring'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/users'
    | '/app/notifications'
    | '/app/profile'
    | '/org/audit'
    | '/org/billing'
    | '/org/divisions'
    | '/org/settings'
    | '/org/teams'
    | '/org/users'
    | '/org/webhooks'
    | '/org/divisions/$divisionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/org'
    | '/register'
    | '/reset-password'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/_layout'
    | '/app/_layout'
    | '/org/_layout'
    | '/admin/_layout/'
    | '/app/_layout/'
    | '/org/_layout/'
    | '/admin/_layout/organizations/$orgId'
    | '/admin/_layout/teams/$teamId'
    | '/admin/_layout/users/$userId'
    | '/admin/_layout/audit/'
    | '/admin/_layout/divisions/'
    | '/admin/_layout/monitoring/'
    | '/admin/_layout/organizations/'
    | '/admin/_layout/policies/'
    | '/admin/_layout/settings/'
    | '/admin/_layout/teams/'
    | '/admin/_layout/users/'
    | '/app/_layout/notifications/'
    | '/app/_layout/profile/'
    | '/org/_layout/audit/'
    | '/org/_layout/billing/'
    | '/org/_layout/divisions/'
    | '/org/_layout/settings/'
    | '/org/_layout/teams/'
    | '/org/_layout/users/'
    | '/org/_layout/webhooks/'
    | '/org/_layout/divisions/$divisionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrgRoute: typeof OrgRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/_layout': {
      id: '/org/_layout'
      path: ''
      fullPath: '/org'
      preLoaderRoute: typeof OrgLayoutRouteImport
      parentRoute: typeof OrgRoute
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/org/_layout/': {
      id: '/org/_layout/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgLayoutIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/org/_layout/webhooks/': {
      id: '/org/_layout/webhooks/'
      path: '/webhooks'
      fullPath: '/org/webhooks'
      preLoaderRoute: typeof OrgLayoutWebhooksIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/users/': {
      id: '/org/_layout/users/'
      path: '/users'
      fullPath: '/org/users'
      preLoaderRoute: typeof OrgLayoutUsersIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/teams/': {
      id: '/org/_layout/teams/'
      path: '/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof OrgLayoutTeamsIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/settings/': {
      id: '/org/_layout/settings/'
      path: '/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgLayoutSettingsIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/divisions/': {
      id: '/org/_layout/divisions/'
      path: '/divisions'
      fullPath: '/org/divisions'
      preLoaderRoute: typeof OrgLayoutDivisionsIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/billing/': {
      id: '/org/_layout/billing/'
      path: '/billing'
      fullPath: '/org/billing'
      preLoaderRoute: typeof OrgLayoutBillingIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/org/_layout/audit/': {
      id: '/org/_layout/audit/'
      path: '/audit'
      fullPath: '/org/audit'
      preLoaderRoute: typeof OrgLayoutAuditIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
    '/app/_layout/profile/': {
      id: '/app/_layout/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppLayoutProfileIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/notifications/': {
      id: '/app/_layout/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppLayoutNotificationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/teams/': {
      id: '/admin/_layout/teams/'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminLayoutTeamsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings/': {
      id: '/admin/_layout/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/policies/': {
      id: '/admin/_layout/policies/'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminLayoutPoliciesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/organizations/': {
      id: '/admin/_layout/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminLayoutOrganizationsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/monitoring/': {
      id: '/admin/_layout/monitoring/'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminLayoutMonitoringIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/divisions/': {
      id: '/admin/_layout/divisions/'
      path: '/divisions'
      fullPath: '/admin/divisions'
      preLoaderRoute: typeof AdminLayoutDivisionsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/audit/': {
      id: '/admin/_layout/audit/'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminLayoutAuditIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/users/$userId': {
      id: '/admin/_layout/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminLayoutUsersUserIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/teams/$teamId': {
      id: '/admin/_layout/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminLayoutTeamsTeamIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/organizations/$orgId': {
      id: '/admin/_layout/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminLayoutOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/org/_layout/divisions/$divisionId/': {
      id: '/org/_layout/divisions/$divisionId/'
      path: '/divisions/$divisionId'
      fullPath: '/org/divisions/$divisionId'
      preLoaderRoute: typeof OrgLayoutDivisionsDivisionIdIndexRouteImport
      parentRoute: typeof OrgLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutOrganizationsOrgIdRoute: typeof AdminLayoutOrganizationsOrgIdRoute
  AdminLayoutTeamsTeamIdRoute: typeof AdminLayoutTeamsTeamIdRoute
  AdminLayoutUsersUserIdRoute: typeof AdminLayoutUsersUserIdRoute
  AdminLayoutAuditIndexRoute: typeof AdminLayoutAuditIndexRoute
  AdminLayoutDivisionsIndexRoute: typeof AdminLayoutDivisionsIndexRoute
  AdminLayoutMonitoringIndexRoute: typeof AdminLayoutMonitoringIndexRoute
  AdminLayoutOrganizationsIndexRoute: typeof AdminLayoutOrganizationsIndexRoute
  AdminLayoutPoliciesIndexRoute: typeof AdminLayoutPoliciesIndexRoute
  AdminLayoutSettingsIndexRoute: typeof AdminLayoutSettingsIndexRoute
  AdminLayoutTeamsIndexRoute: typeof AdminLayoutTeamsIndexRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutOrganizationsOrgIdRoute: AdminLayoutOrganizationsOrgIdRoute,
  AdminLayoutTeamsTeamIdRoute: AdminLayoutTeamsTeamIdRoute,
  AdminLayoutUsersUserIdRoute: AdminLayoutUsersUserIdRoute,
  AdminLayoutAuditIndexRoute: AdminLayoutAuditIndexRoute,
  AdminLayoutDivisionsIndexRoute: AdminLayoutDivisionsIndexRoute,
  AdminLayoutMonitoringIndexRoute: AdminLayoutMonitoringIndexRoute,
  AdminLayoutOrganizationsIndexRoute: AdminLayoutOrganizationsIndexRoute,
  AdminLayoutPoliciesIndexRoute: AdminLayoutPoliciesIndexRoute,
  AdminLayoutSettingsIndexRoute: AdminLayoutSettingsIndexRoute,
  AdminLayoutTeamsIndexRoute: AdminLayoutTeamsIndexRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutNotificationsIndexRoute: typeof AppLayoutNotificationsIndexRoute
  AppLayoutProfileIndexRoute: typeof AppLayoutProfileIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutNotificationsIndexRoute: AppLayoutNotificationsIndexRoute,
  AppLayoutProfileIndexRoute: AppLayoutProfileIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OrgLayoutRouteChildren {
  OrgLayoutIndexRoute: typeof OrgLayoutIndexRoute
  OrgLayoutAuditIndexRoute: typeof OrgLayoutAuditIndexRoute
  OrgLayoutBillingIndexRoute: typeof OrgLayoutBillingIndexRoute
  OrgLayoutDivisionsIndexRoute: typeof OrgLayoutDivisionsIndexRoute
  OrgLayoutSettingsIndexRoute: typeof OrgLayoutSettingsIndexRoute
  OrgLayoutTeamsIndexRoute: typeof OrgLayoutTeamsIndexRoute
  OrgLayoutUsersIndexRoute: typeof OrgLayoutUsersIndexRoute
  OrgLayoutWebhooksIndexRoute: typeof OrgLayoutWebhooksIndexRoute
  OrgLayoutDivisionsDivisionIdIndexRoute: typeof OrgLayoutDivisionsDivisionIdIndexRoute
}

const OrgLayoutRouteChildren: OrgLayoutRouteChildren = {
  OrgLayoutIndexRoute: OrgLayoutIndexRoute,
  OrgLayoutAuditIndexRoute: OrgLayoutAuditIndexRoute,
  OrgLayoutBillingIndexRoute: OrgLayoutBillingIndexRoute,
  OrgLayoutDivisionsIndexRoute: OrgLayoutDivisionsIndexRoute,
  OrgLayoutSettingsIndexRoute: OrgLayoutSettingsIndexRoute,
  OrgLayoutTeamsIndexRoute: OrgLayoutTeamsIndexRoute,
  OrgLayoutUsersIndexRoute: OrgLayoutUsersIndexRoute,
  OrgLayoutWebhooksIndexRoute: OrgLayoutWebhooksIndexRoute,
  OrgLayoutDivisionsDivisionIdIndexRoute:
    OrgLayoutDivisionsDivisionIdIndexRoute,
}

const OrgLayoutRouteWithChildren = OrgLayoutRoute._addFileChildren(
  OrgLayoutRouteChildren,
)

interface OrgRouteChildren {
  OrgLayoutRoute: typeof OrgLayoutRouteWithChildren
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgLayoutRoute: OrgLayoutRouteWithChildren,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrgRoute: OrgRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
